In [35]:
import numpy as np
import time
import random
import sys
import heapq

In [36]:
def generate_random_graph(num_vertices, num_edges):
    # Initialize the adjacency matrix with zeros
    adjacency_matrix = np.zeros((num_vertices, num_vertices), dtype=int)

    # Generate random edges
    edges = 0
    while edges < num_edges:
        # Randomly select two vertices
        vertex1, vertex2 = random.sample(range(num_vertices), 2)

        # Check if an edge already exists between the two vertices
        if adjacency_matrix[vertex1][vertex2] == 0 and vertex1 != vertex2:
            # Generate a random weight for the edge
            weight = random.randint(1, 100)

            # Assign the weight to both positions in the adjacency matrix (symmetric)
            adjacency_matrix[vertex1][vertex2] = weight
            adjacency_matrix[vertex2][vertex1] = weight

            edges += 1

    return adjacency_matrix

# Generate a random adjacency matrix for a graph with 100 vertices and 500 edges
adjacency_matrix = generate_random_graph(100, 500)

# Print the adjacency matrix
print(adjacency_matrix)

[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0 85  0]
 [ 0  0  0 ... 85  0  0]
 [ 0  0  0 ...  0  0  0]]


In [37]:
def dijkstra(adjacency_matrix, start_vertex):
    num_vertices = len(adjacency_matrix)
    visited = [False] * num_vertices
    distance = [sys.maxsize] * num_vertices
    distance[start_vertex] = 0

    for _ in range(num_vertices):
        min_distance = sys.maxsize
        min_vertex = -1

        # Find the vertex with the minimum distance
        for v in range(num_vertices):
            if not visited[v] and distance[v] < min_distance:
                min_distance = distance[v]
                min_vertex = v

        visited[min_vertex] = True

        # Update the distances of neighboring vertices
        for v in range(num_vertices):
            if (
                not visited[v]
                and adjacency_matrix[min_vertex][v] != 0
                and distance[min_vertex] + adjacency_matrix[min_vertex][v] < distance[v]
            ):
                distance[v] = distance[min_vertex] + adjacency_matrix[min_vertex][v]

    return distance

def bellman_ford(adjacency_matrix, start_vertex):
    num_vertices = len(adjacency_matrix)
    distance = [sys.maxsize] * num_vertices
    distance[start_vertex] = 0

    for _ in range(num_vertices - 1):
        for u in range(num_vertices):
            for v in range(num_vertices):
                if (
                    distance[u] != sys.maxsize
                    and adjacency_matrix[u][v] != 0
                    and distance[u] + adjacency_matrix[u][v] < distance[v]
                ):
                    distance[v] = distance[u] + adjacency_matrix[u][v]

    return distance

# Generate a random adjacency matrix for a graph with 100 vertices and 500 edges
num_vertices = 100
num_edges = 500

edges = 0
while edges < num_edges:
    vertex1, vertex2 = random.sample(range(num_vertices), 2)
    if adjacency_matrix[vertex1][vertex2] == 0 and vertex1 != vertex2:
        weight = random.randint(1, 100)
        adjacency_matrix[vertex1][vertex2] = weight
        adjacency_matrix[vertex2][vertex1] = weight
        edges += 1

# Random starting vertex
start_vertex = random.randint(0, num_vertices - 1)

# Find shortest paths using Dijkstra's algorithm
dijkstra_distances = dijkstra(adjacency_matrix, start_vertex)

# Find shortest paths using Bellman-Ford algorithm
bellman_ford_distances = bellman_ford(adjacency_matrix, start_vertex)

# Print the shortest distances from the starting vertex to all other vertices
print("Dijkstra's algorithm:")
print(dijkstra_distances)
print("\nBellman-Ford algorithm:")
print(bellman_ford_distances)

Dijkstra's algorithm:
[10, 24, 40, 41, 20, 28, 18, 30, 23, 30, 30, 24, 29, 10, 25, 22, 35, 26, 26, 14, 30, 12, 20, 49, 31, 30, 22, 26, 55, 24, 25, 23, 22, 25, 7, 29, 22, 9, 37, 17, 27, 28, 21, 14, 35, 25, 29, 45, 35, 24, 25, 33, 26, 16, 44, 41, 31, 23, 19, 25, 22, 46, 26, 28, 20, 32, 5, 20, 16, 30, 37, 34, 31, 36, 0, 25, 16, 15, 20, 38, 21, 27, 25, 30, 38, 23, 44, 14, 32, 29, 11, 25, 23, 36, 20, 16, 17, 25, 15, 42]

Bellman-Ford algorithm:
[10, 24, 40, 41, 20, 28, 18, 30, 23, 30, 30, 24, 29, 10, 25, 22, 35, 26, 26, 14, 30, 12, 20, 49, 31, 30, 22, 26, 55, 24, 25, 23, 22, 25, 7, 29, 22, 9, 37, 17, 27, 28, 21, 14, 35, 25, 29, 45, 35, 24, 25, 33, 26, 16, 44, 41, 31, 23, 19, 25, 22, 46, 26, 28, 20, 32, 5, 20, 16, 30, 37, 34, 31, 36, 0, 25, 16, 15, 20, 38, 21, 27, 25, 30, 38, 23, 44, 14, 32, 29, 11, 25, 23, 36, 20, 16, 17, 25, 15, 42]


In [38]:
# Experiment parameters
num_experiments = 10

# Variables to store total time
dijkstra_total_time = 0
bellman_ford_total_time = 0

# Repeat the experiment multiple times
for _ in range(num_experiments):
    # Measure the time required for Dijkstra's algorithm
    start_time = time.time()
    dijkstra_distances = dijkstra(adjacency_matrix, start_vertex)
    end_time = time.time()
    dijkstra_total_time += end_time - start_time

    # Measure the time required for Bellman-Ford algorithm
    start_time = time.time()
    bellman_ford_distances = bellman_ford(adjacency_matrix, start_vertex)
    end_time = time.time()
    bellman_ford_total_time += end_time - start_time

# Calculate the average time required for each algorithm
dijkstra_average_time = dijkstra_total_time / num_experiments
bellman_ford_average_time = bellman_ford_total_time / num_experiments

# Print the average time required for each algorithm
print("Average time for Dijkstra's algorithm:", dijkstra_average_time)
print("Average time for Bellman-Ford algorithm:", bellman_ford_average_time)

Average time for Dijkstra's algorithm: 0.009218335151672363
Average time for Bellman-Ford algorithm: 2.6083356857299806


In [39]:
# Define the cell grid dimensions
num_rows = 10
num_cols = 20

def generate_grid(num_rows, num_cols, num_obstacles):
    # Initialize the grid with all cells set to 0 (empty)
    grid = np.zeros((num_rows, num_cols), dtype=int)

    # Generate random obstacle cells
    obstacles = random.sample(range(num_rows * num_cols), num_obstacles)

    # Set obstacle cells to 1
    for obstacle in obstacles:
        row = obstacle // num_cols
        col = obstacle % num_cols
        grid[row][col] = 1

    return grid

def heuristic(cell, goal):
    # Calculate the Manhattan distance heuristic between two cells
    return abs(cell[0] - goal[0]) + abs(cell[1] - goal[1])

def get_neighbors(cell, grid):
    # Get the valid neighbors of a cell in the grid
    row, col = cell
    neighbors = []

    if row > 0 and grid[row - 1][col] == 0:  # Up
        neighbors.append((row - 1, col))
    if row < num_rows - 1 and grid[row + 1][col] == 0:  # Down
        neighbors.append((row + 1, col))
    if col > 0 and grid[row][col - 1] == 0:  # Left
        neighbors.append((row, col - 1))
    if col < num_cols - 1 and grid[row][col + 1] == 0:  # Right
        neighbors.append((row, col + 1))

    return neighbors

def a_star(grid, start_cell, goal_cell):
    # Initialize the data structures
    open_set = []
    closed_set = set()
    came_from = {}

    g_score = {start_cell: 0}
    f_score = {start_cell: heuristic(start_cell, goal_cell)}

    # Add the start cell to the open set
    heapq.heappush(open_set, (f_score[start_cell], start_cell))

    # A* algorithm
    while open_set:
        _, current = heapq.heappop(open_set)

        if current == goal_cell:
            # Reached the goal, reconstruct the path
            path = [current]
            while current in came_from:
                current = came_from[current]
                path.append(current)
            path.reverse()
            return path

        closed_set.add(current)

        for neighbor in get_neighbors(current, grid):
            # Calculate the tentative g score for the neighbor
            tentative_g_score = g_score[current] + 1

            if neighbor in closed_set and tentative_g_score >= g_score.get(neighbor, float('inf')):
                # This is not a better path
                continue

            if tentative_g_score < g_score.get(neighbor, float('inf')):
                # Found a better path to the neighbor
                came_from[neighbor] = current
                g_score[neighbor] = tentative_g_score
                f_score[neighbor] = tentative_g_score + heuristic(neighbor, goal_cell)
                if neighbor not in open_set:
                    heapq.heappush(open_set, (f_score[neighbor], neighbor))

    # No path found
    return None

# Generate a grid with 10x20 cells and 40 obstacle cells
num_obstacles = 40
grid = generate_grid(num_rows, num_cols, num_obstacles)

# Choose two random non-obstacle cells as the start and goal
valid_cells = [(row, col) for row in range(num_rows) for col in range(num_cols) if grid[row][col] == 0]
start_cell, goal_cell = random.sample(valid_cells, 2)

# Find the shortest path using the A* algorithm
path = a_star(grid, start_cell, goal_cell)

# Print the grid with the path
for row in range(num_rows):
    for col in range(num_cols):
        if grid[row][col] == 1:
            print("#", end=" ")  # Obstacle cell
        elif (row, col) == start_cell:
            print("S", end=" ")  # Start cell
        elif (row, col) == goal_cell:
            print("G", end=" ")  # Goal cell
        elif (row, col) in path:
            print("*", end=" ")  # Path cell
        else:
            print(".", end=" ")  # Empty cell
    print()
print("dots represent empty cells, # represents obstacles, S represents start cell, G represents goal cell, and * represents the path")

. # . . # . . . . . . # . . . . # . . . 
. . . . . # . . . . . # * * * * * * . . 
# . . . . # . # * * * * * . . . # * * . 
. . . . . . . * * . . . . . # . . # * . 
. . # . . . # * . . . . . # . . # * * . 
. . # . . # . * . . . . . # # # . * # # 
. # . # . . . * . # # . # . . . # * . . 
. . . . . . . G . . # # . . . . * * # . 
. # # . . . . . . . # . . . . . S . . . 
. . . . . . # . # . # . . . . . # . # . 
dots represent empty cells, # represents obstacles, S represents start cell, G represents goal cell, and * represents the path


In [40]:
# Experiment parameters
num_experiments = 5

# Variables to store the total number of successful paths and total path lengths
num_successful_paths = 0
total_path_length = 0

# Repeat the experiment multiple times
start_time = time.time()
for _ in range(num_experiments):
    # Generate a grid with 10x20 cells and 40 obstacle cells
    num_obstacles = 40
    grid = generate_grid(num_rows, num_cols, num_obstacles)

    # Choose two random non-obstacle cells as the start and goal
    valid_cells = [(row, col) for row in range(num_rows) for col in range(num_cols) if grid[row][col] == 0]
    start_cell, goal_cell = random.sample(valid_cells, 2)

    # Find the shortest path using the A* algorithm
    path = a_star(grid, start_cell, goal_cell)

    if path is not None:
        # Increment the number of successful paths and update the total path length
        num_successful_paths += 1
        total_path_length += len(path)
        
end_time = time.time()
average_execution_time = (end_time - start_time) / num_experiments

# Calculate the average path length
average_path_length = total_path_length / num_successful_paths if num_successful_paths > 0 else 0

# Analyze the results
print("Experiment Results:")
print("Number of Successful Paths:", num_successful_paths)
print("Average Path Length:", average_path_length)
print("Average Execution Time:", average_execution_time)

Experiment Results:
Number of Successful Paths: 5
Average Path Length: 9.6
Average Execution Time: 0.00020003318786621094
